### 리그 정보
POST http://localhost:8080/crawl/league

### 토너 먼트 정보
POST http://localhost:8080/crawl/tournament?leagueId=98767991310872058

### 팀 정보
POST http://localhost:8080/crawl/team-player?leagueName=LCK

### 팀 정보 디테일
POST http://localhost:8080/crawl/team/detail/lck

### 선수 정보 디테일
POST http://localhost:8080/crawl/player/detail/lck

### 매치 정보
POST http://localhost:8080/crawl/match?tournamentId=105522984810490982

### 게임 정보 전체
POST http://localhost:8080/crawl/game

### 게임 매치 히스토리 링크 찾기
POST http://localhost:8080/crawl/match-history-link/lck

### 게임 매치 히스토리
POST http://localhost:8080/crawl/match-history
Content-Type: application/json

{
    "matchId": "105522984812916089"
}



