package com.kingjakeu.lolesport.common.constant;

import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
public enum CrawlUrlConfig {
    LOL_GAMEPEDIA,
    LCK_TEAM_LIST,
    LCK_MATCH_HISTORY_LIST,

    LEAGUE_LIST,

    TOURNAMENT_LIST,

    LEAGUE_SCHEDULE_LIST,

    TEAM_INFO_LIST,

    MATCH_EVENT_DETAIL,

    MATCH_HISTORY_PAGE_BASE,
    MATCH_HISTORY_API_BASE,

    GAME_COMPONENT_BASE,
    GAME_COMPONENT_CHAMPION,
    GAME_COMPONENT_RUNE,
    GAME_COMPONENT_ITEM,

    GAME_COMPONENT_CHAMPION_PATCH,
    GAME_COMPONENT_ITEM_PATCH,
    GAME_COMPONENT_RUNE_PATCH,

    GAME_COMPONENT_KOR,

    ;
}
