spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:mariadb://lolesport.cgcrmk7vdleu.ap-northeast-2.rds.amazonaws.com:3306/lolesports
        driver-class-name: org.mariadb.jdbc.Driver
        username: admin #lolesports
        password: aktmxj12! #lol2012
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update

# log properties
logging:
    level:
        root: info
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: trace